### ISSUE TITLE
推介几本Java 语言相关的REST的书籍

### ISSUE THREAD

**Issue by waylau** [aisuhua/restful-api-design-references#2]
* [Jersey 2.x 用户指南](https://github.com/waylau/Jersey-2.x-User-Guide)

该书是 Java REST 的规范实现之一 Jersey 用户手册，中文翻译

* [REST 实战](https://github.com/waylau/rest-in-action)
该书是基于 Jersey 的中文开源REST实战书籍

**Comment by aisuhua** [comment]
Thanks! 谢谢
