### ISSUE TITLE
https://github.com/waylau/RestDemo

### ISSUE THREAD

**Issue by waylau** [aisuhua/restful-api-design-references#3]
推荐

https://github.com/waylau/RestDemo

RESTful Web Service Demos with Jersey ,Hibernate,Mysql,SQLserver,jQuery,AangularJS,Boostrap...构建REST服务（实例）

**Comment by aisuhua** [comment]
谢谢！

**Comment by waylau** [comment]
@aisuhua 

我看你是这样放的

“REST 实战 基于 Jersey 构建 RESTful 服务，有实际的案例 RestDemo（我注：读者需要懂一些 Java ）”

其实 《REST 实战》   和 《RestDemo》 应该是两篇完全不同的教程。RestDemo 不是  《REST 实战》  中的示例。两篇教程有各自的示例

**Comment by aisuhua** [comment]
是的。刚开始并没有仔细看过，我是按照项目的描述添加进来的。

我可以这样认为吗？
“REST 实战” 和 “RestDemo” 都是对书籍《Jersey 2.x 用户指南》的一些实战和运用实例。它们可以使读者更好地理解 Jersey ，以及如何在项目中运用 Jersey。

如果是这样，那么就把 “REST 实战” 和 “RestDemo” 作为 《Jersey 2.x 用户指南》 的辅助案例，不独立列出。

如果不是的话，欢迎提 PR。

ps：其实，我希望这个仓库，能够收集多一些单纯介绍 REST 的文献。如果与编程语言密切相关的话，可能会对一些读者造成阅读上的压力。以后或者也可以考虑新开一个仓库，来专门收集一些优秀的 REST 项目。

谢谢！

**Comment by waylau** [comment]
@aisuhua  


Jersey 确实是 Java 语言 REST 规范的实现。

《Jersey 2.x 用户指南》 是官方出品的用户指南，里面是会全面讲解 Jersey  的功能原理，但也止于 Jersey。
《RestDemo》 是 基于 Jersey 、spring 、hibernate 等开源框架构建一个完整 RESTful 的综合应用的介绍。
《REST 实战》这本开源书，是主要基于 Jersey 来讲解一些具体的应用实例，这些实例要比《Jersey 2.x 用户指南》 里面讲得更加深入以及更加贴合实际运行。毕竟，在现实应用中，并不是所有的Jersey  的功能都能运用到。


考虑到你这个站目的，就按照你所说的 ““REST 实战” 和 “RestDemo” 都是对书籍《Jersey 2.x 用户指南》的一些实战和运用实例” 这样来排版也行。
